swagger: '2.0'

info:
  version: '1.0'
  title: Dave
  description: ''
  license:
    name: MIT
    url: https://github.com/chrisrcoles/dave-api
host: localhost:8081
basePath: /api/v1/
schemes:
- http
- https
consumes:
- application/json
produces:
- application/json

paths:
  /health:
    get:
      description: Health Endpoint
      summary: Get Health Status
      tags:
      - health
      operationId: index_getHealth
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/Health'
  /sightings:
    post:
      description: Create a bear sighting
      summary: Bear Sighting Create
      tags:
      - bearsightings
      operationId: index_createBearSighting
      parameters:
      - $ref: "#/parameters/BearSightingCreateBody"
      produces:
      - application/json
      responses:
        201:
          $ref: '#/responses/BearSighting'
  /sightings/{id}:
    get:
      description: Get a bear sighting by id
      summary: Get bear sighting
      tags:
      - bearsightings
      operationId: index_getBearSighting
      parameters:
      - $ref: '#/parameters/Id'
      produces:
      - application/json
      responses:
        200:
          description: 'Resource found'
          schema:
            $ref: '#/responses/BearSighting'
        404:
          $ref: '#/responses/FoundErrors'
  /sightings/search:
    get:
      description: Get a bear sighting by searching
      summary: Get bear sighting with query params
      tags:
      - bearsightings
      operationId: index_searchBearSightings
      parameters:
      - $ref: '#/parameters/QueryStartDate'
      - $ref: '#/parameters/QueryEndDate'
      - $ref: '#/parameters/QueryBearType'
      - $ref: '#/parameters/QueryZipCode'
      - $ref: '#/parameters/QuerySort'
      produces:
      - application/json
      responses:
        200:
          description: 'Resource found'
          schema:
            $ref: '#/responses/BearSighting'
        404:
          $ref: '#/responses/FoundErrors'
parameters:
# path
  Id:
    name: id
    in: path
    required: true
    type: string
    description: Resource ID
  BearSightingCreateBody:
    name: body
    in: body
    required: true
    schema:
      $ref: '#/definitions/BearSighting'
  QueryStartDate:
    name: start_date
    in: query
    required: false
    type: string
    description: Query for bear sighting start date
  QueryEndDate:
    name: end_date
    in: query
    required: false
    type: string
    description: Query for bear sighting end date
  QueryBearType:
    name: bear_type
    in: query
    required: false
    type: string
    description: Query for bear type
  QueryZipCode:
    name: zipcode
    in: query
    required: false
    type: string
    description: Query for zip code
  QuerySort:
    name: sort
    in: query
    required: false
    type: string
    description: Query for sort
definitions:
  Health:
    title: Health
    type: object
    properties:
      uptime:
        description: ''
        type: number
        format: double
      env:
        description: ''
        type: string
      rand:
        description: ''
        type: number
        format: double
    required:
    - uptime
    - env
    - rand
  BearSighting:
    title: Bear Sighting
    type: object
    description: Request body for user signup
    properties:
      bear_type:
        description: Type of bear
        type: string
      notes:
        description: Notes on bear sighting
        type: string
      zipcode:
        description: Zipcode bear sighting occurred in
        type: string
      num_bears:
        description: Number of bears seen at sighting
        type: integer
      start_date:
        description: Start date of bear sighting
        type: string
      end_date:
        description: End date of bear sighting
        type: string
      created_at:
        description: Time of creation
        type: string
      updated_at:
        description: Time of last update
        type: string
    required:
      - bear_type
      - notes
      - zipcode
      - num_bears
  Error:
    title: Error
    description: Expected error response object
    type: object
    properties:
      id:
        description: Unique ID for this instance of the error
        type: string
      message:
        description: Common error type
        type: string
      description:
        description: Detailed explanation of the error
        type: string
      meta:
        description: Optional meta data for the error
        type: object
  ErrorArray:
    title: Errors
    description: Array of error response objects
    type: array
    items:
      $ref: '#/definitions/Error'

responses:
   FoundErrors:
       description: Resource could not be found
       schema:
         type: object
         properties:
           errors:
             $ref: '#/definitions/ErrorArray'
         required:
         - errors
   BearSighting:
       description: Return a single bear sighting
       schema:
         $ref: '#/definitions/BearSighting'
   BearSightings:
       description: Return an array of bear sightings
       schema:
         $ref: '#/definitions/BearSighting'
